// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"RunnerGo-management/internal/pkg/dal/model"
)

func newUserEverydayActivity(db *gorm.DB, opts ...gen.DOOption) userEverydayActivity {
	_userEverydayActivity := userEverydayActivity{}

	_userEverydayActivity.userEverydayActivityDo.UseDB(db, opts...)
	_userEverydayActivity.userEverydayActivityDo.UseModel(&model.UserEverydayActivity{})

	tableName := _userEverydayActivity.userEverydayActivityDo.TableName()
	_userEverydayActivity.ALL = field.NewAsterisk(tableName)
	_userEverydayActivity.ID = field.NewInt32(tableName, "id")
	_userEverydayActivity.UserID = field.NewString(tableName, "user_id")
	_userEverydayActivity.CreatedAt = field.NewTime(tableName, "created_at")
	_userEverydayActivity.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userEverydayActivity.DeletedAt = field.NewField(tableName, "deleted_at")

	_userEverydayActivity.fillFieldMap()

	return _userEverydayActivity
}

type userEverydayActivity struct {
	userEverydayActivityDo userEverydayActivityDo

	ALL       field.Asterisk
	ID        field.Int32  // 主键ID
	UserID    field.String // 用户ID
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 修改时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (u userEverydayActivity) Table(newTableName string) *userEverydayActivity {
	u.userEverydayActivityDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userEverydayActivity) As(alias string) *userEverydayActivity {
	u.userEverydayActivityDo.DO = *(u.userEverydayActivityDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userEverydayActivity) updateTableName(table string) *userEverydayActivity {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.UserID = field.NewString(table, "user_id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")

	u.fillFieldMap()

	return u
}

func (u *userEverydayActivity) WithContext(ctx context.Context) *userEverydayActivityDo {
	return u.userEverydayActivityDo.WithContext(ctx)
}

func (u userEverydayActivity) TableName() string { return u.userEverydayActivityDo.TableName() }

func (u userEverydayActivity) Alias() string { return u.userEverydayActivityDo.Alias() }

func (u *userEverydayActivity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userEverydayActivity) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 5)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
}

func (u userEverydayActivity) clone(db *gorm.DB) userEverydayActivity {
	u.userEverydayActivityDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userEverydayActivity) replaceDB(db *gorm.DB) userEverydayActivity {
	u.userEverydayActivityDo.ReplaceDB(db)
	return u
}

type userEverydayActivityDo struct{ gen.DO }

func (u userEverydayActivityDo) Debug() *userEverydayActivityDo {
	return u.withDO(u.DO.Debug())
}

func (u userEverydayActivityDo) WithContext(ctx context.Context) *userEverydayActivityDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userEverydayActivityDo) ReadDB() *userEverydayActivityDo {
	return u.Clauses(dbresolver.Read)
}

func (u userEverydayActivityDo) WriteDB() *userEverydayActivityDo {
	return u.Clauses(dbresolver.Write)
}

func (u userEverydayActivityDo) Session(config *gorm.Session) *userEverydayActivityDo {
	return u.withDO(u.DO.Session(config))
}

func (u userEverydayActivityDo) Clauses(conds ...clause.Expression) *userEverydayActivityDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userEverydayActivityDo) Returning(value interface{}, columns ...string) *userEverydayActivityDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userEverydayActivityDo) Not(conds ...gen.Condition) *userEverydayActivityDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userEverydayActivityDo) Or(conds ...gen.Condition) *userEverydayActivityDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userEverydayActivityDo) Select(conds ...field.Expr) *userEverydayActivityDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userEverydayActivityDo) Where(conds ...gen.Condition) *userEverydayActivityDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userEverydayActivityDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *userEverydayActivityDo {
	return u.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (u userEverydayActivityDo) Order(conds ...field.Expr) *userEverydayActivityDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userEverydayActivityDo) Distinct(cols ...field.Expr) *userEverydayActivityDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userEverydayActivityDo) Omit(cols ...field.Expr) *userEverydayActivityDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userEverydayActivityDo) Join(table schema.Tabler, on ...field.Expr) *userEverydayActivityDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userEverydayActivityDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userEverydayActivityDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userEverydayActivityDo) RightJoin(table schema.Tabler, on ...field.Expr) *userEverydayActivityDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userEverydayActivityDo) Group(cols ...field.Expr) *userEverydayActivityDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userEverydayActivityDo) Having(conds ...gen.Condition) *userEverydayActivityDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userEverydayActivityDo) Limit(limit int) *userEverydayActivityDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userEverydayActivityDo) Offset(offset int) *userEverydayActivityDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userEverydayActivityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userEverydayActivityDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userEverydayActivityDo) Unscoped() *userEverydayActivityDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userEverydayActivityDo) Create(values ...*model.UserEverydayActivity) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userEverydayActivityDo) CreateInBatches(values []*model.UserEverydayActivity, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userEverydayActivityDo) Save(values ...*model.UserEverydayActivity) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userEverydayActivityDo) First() (*model.UserEverydayActivity, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserEverydayActivity), nil
	}
}

func (u userEverydayActivityDo) Take() (*model.UserEverydayActivity, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserEverydayActivity), nil
	}
}

func (u userEverydayActivityDo) Last() (*model.UserEverydayActivity, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserEverydayActivity), nil
	}
}

func (u userEverydayActivityDo) Find() ([]*model.UserEverydayActivity, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserEverydayActivity), err
}

func (u userEverydayActivityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserEverydayActivity, err error) {
	buf := make([]*model.UserEverydayActivity, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userEverydayActivityDo) FindInBatches(result *[]*model.UserEverydayActivity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userEverydayActivityDo) Attrs(attrs ...field.AssignExpr) *userEverydayActivityDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userEverydayActivityDo) Assign(attrs ...field.AssignExpr) *userEverydayActivityDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userEverydayActivityDo) Joins(fields ...field.RelationField) *userEverydayActivityDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userEverydayActivityDo) Preload(fields ...field.RelationField) *userEverydayActivityDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userEverydayActivityDo) FirstOrInit() (*model.UserEverydayActivity, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserEverydayActivity), nil
	}
}

func (u userEverydayActivityDo) FirstOrCreate() (*model.UserEverydayActivity, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserEverydayActivity), nil
	}
}

func (u userEverydayActivityDo) FindByPage(offset int, limit int) (result []*model.UserEverydayActivity, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userEverydayActivityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userEverydayActivityDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userEverydayActivityDo) Delete(models ...*model.UserEverydayActivity) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userEverydayActivityDo) withDO(do gen.Dao) *userEverydayActivityDo {
	u.DO = *do.(*gen.DO)
	return u
}
